language: objective-c
osx_image: xcode11.3
env:
  - XCODE_SCHEME=osia
    XCODE_PROJECT=Swift/osia.xcodeproj
    XCODE_DESTINATION="platform=iOS Simulator,OS=13.3,name=iPhone 11"
script:
  - xcodebuild clean -project "$XCODE_PROJECT"
  - set -o pipefail && xcodebuild build -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -destination "$XCODE_DESTINATION" | xcpretty -s
