language: objective-c
osx_image: xcode9.2
env:
  - XCODE_SCHEME=osia
    XCODE_PROJECT=Swift/osia.xcodeproj
    XCODE_DESTINATION="platform=iOS Simulator,OS=11.2,name=iPhone 8"
script:
  - xcodebuild clean -project "$XCODE_PROJECT"
  - set -o pipefail && xcodebuild build -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -destination "$XCODE_DESTINATION" | xcpretty -s
