name: Xcode test

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_11.4.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Xcode unit tests
      run: |
        cd Swift/
        xcodebuild clean test -scheme osia -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.4'

    - uses: actions/upload-artifact@v2
      with:
        name: tests.xcresult
        path: /Users/runner/Library/Developer/Xcode/DerivedData/*/Logs/Test/*.xcresult
