name: Xcode build iOS 14

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Xcode build
      run: |
        cd Swift/
        xcodebuild clean build -scheme osia -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4'
